git remote add origin git@github.com:damotatts-cyber/Update.git
git branch -M main
git push -u origin mainname: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
